INSERT INTO public."user" (id, role, full_name, username, inserted_at, updated_at) values 
(public.gen_random_uuid(),'volunteer','Vladimir Zbrancea', 'vladimir.zbrancea', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Celia Blacu', 'celia.blacu', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Diana Bob', 'diana.bob', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Iolanda Marian', 'iolanda.marian', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Raluca Pacurar', 'raluca.pacurar', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Mihaela Anca Balc', 'mihaela.anca.balc', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Calin Manea', 'calin.manea', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Mara Negrea', 'mara.negrea', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Dana Bizuleanu', 'dana.bizuleanu', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Iulia Catana', 'iulia.catana', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Raluca Tarnoveanu', 'raluca.tarnoveanu', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Laura Muresan', 'laura.muresan', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Csilla Turos', 'csilla.turos', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Alexandra Berecski', 'alexandra.berecski', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Carla Humita', 'carla.humita', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Andrada Iacovache', 'andrada.iacovache', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Anna M Metz', 'anna.m.metz', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Daniela Pasc', 'daniela.pasc', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Mara Arisa', 'mara.arisa', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Ioana Iulia Lung', 'ioana.iulia.lung', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Laura Popovici', 'laura.popovici', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Hilda Fulop', 'hilda.fulop', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Andreea Pribilean', 'andreea.pribilean', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Andreea Cozma', 'andreea.cozma', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Luminita Sorina Molnar', 'luminita.sorina.molnar', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Roxana Patrut', 'roxana.patrut', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Aristo Cats', 'aristo.cats', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Ildiko Teleky', 'ildiko.teleky', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Oana Pop', 'oana.pop', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Cristina Iepure', 'cristina.iepure', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Vinicius Daniel Dunca', 'vinicius.daniel.dunca', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Isabela Buzila', 'isabela.buzila', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Anca Popescu', 'anca.popescu', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Marius Conkan', 'marius.conkan', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Laura Simon', 'laura.simon', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Gratiella Seiche', 'gratiella.seiche', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Laura Badiu', 'laura.badiu', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Larisa Rus', 'larisa.rus', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Corina Ilea', 'corina.ilea', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Mara Andreicut Pricop', 'mara.andreicut.pricop', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Paul Felecan', 'paul.felecan', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Ildiko Szabo Kis', 'ildiko.szabo.kis', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Ildiko Simon', 'ildiko.simon', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Ramona Muntean', 'ramona.muntean', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Maria Suciu', 'maria.suciu', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Claudiu Olenici', 'claudiu.olenici', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Andra Dan', 'andra.dan', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Oana Salatig', 'oana.salatig', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Meli David', 'meli.david', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Mihaela Teodoroiu', 'mihaela.teodoroiu', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Florina Cadar', 'florina.cadar', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Silvia Zilwie', 'silvia.zilwie', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Naomi Turcu', 'naomi.turcu', NOW(), NOW()),
(public.gen_random_uuid(),'volunteer','Lavinia Ella Husar-Vastag', 'lavinia.ella.husar-vastag', NOW(), NOW());
